# Glances is an open-source system cross-platform monitoring tool.
# IMPORTANT - If Glances page doesnâ€™t load, allow Glances through firewall. sudo ufw allow 61208
services:
  monitoring:
    container_name: glances
    image: nicolargo/glances:latest-full
    pid: host
    ports:
      - 61208:61208
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GLANCES_OPT=-w
