# Profilarr Configuration management tool that automates importing quality profiles.
# https://hub.docker.com/r/santiagosayshey/profilarr
services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ./profilarr:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - myservernet
networks:
  myservernet:
    external: true
