# Nzbget‚Å† is a usenet downloader.
# https://hub.docker.com/r/linuxserver/nzbget
# Default Username: nzbget Password: tegbzn6789
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nzbget:/config
      - /path/to/data/usenet:/data/usenet
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - myservernet
networks:
  myservernet:
    external: true
